In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

csvpath1 = "Data_Sets/StormEvents2016.csv"
csvpath2 = "Data_Sets/Country_Coordinates.csv"

naturaldisasters_df = pd.read_csv(csvpath1)
countrycoordinates_df = pd.read_csv(csvpath2)

In [2]:
naturaldisasters_df.head(5)

,YEARMONTH,EPISODE_ID,EVENT_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,LON2
0,201603,102667,615187,1,2.82,SSE,ANTIOCH,34.6800,-97.4000,3440800,9724000
1,201603,102667,615188,1,1.84,WSW,SCULLIN,34.5100,-96.8900,3430600,9653400
2,201603,102667,615189,1,0.00,N,CONNERVILLE,34.4500,-96.6300,3427000,9637800
3,201603,102667,615190,1,0.00,N,ATOKA,34.3800,-96.1300,3422800,967800
4,201603,102693,625566,1,3.00,ESE,GASTON,45.4134,-123.0729,4524804,1234374

In [ ]:
countrycoordinates_df.head(5)

In [ ]:
#remove unnecessary columns

naturaldisasters_df = pd.DataFrame(naturaldisasters_df[["YEARMONTH",
                                      "EPISODE_ID",
                                      "EVENT_ID",
                                      "LOCATION",
                                      "LATITUDE",
                                      "LONGITUDE",
                                      "Happiness Score 2017",
                                      "2015_pop_w_depression",
                                      "2016_pop_w_depression"]])
whp_dep_df.head()